player_one:
  default_name: "Player 1"
  name_label_x_position: 20
  name_label_y_position: 20
  card_one_x_position: 12
  card_one_y_position: 40
  card_two_x_position: 95
  card_two_y_position: 40
player_two:
  default_name: "Player 2"
  name_label_x_position: 20
  name_label_y_position: 160
  card_one_x_position: 12
  card_one_y_position: 180
  card_two_x_position: 95
  card_two_y_position: 180